title: "Ziyanali Portfolio"
description: "Ziyanali is a developer and AI enthusiast from Ahmedabad."
author:
  name: "Ziyanali"
  twitter: "_iamziyan"
baseurl: ""
url: ""

plugins:
  - jekyll-seo-tag
  - jekyll-minifier

collections:
  pages:
    output: true
    permalink: /:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  sass_dir: _sass
  style: compressed
